"""criar tabela caso

Revision ID: bafd2d56dc84
Revises: 62d6cc7135bb
Create Date: 2026-09-28 15:59:28.896475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafd2d56dc84'
down_revision: Union[str, Sequence[str], None] = '62d6cc7135bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo_atendimento', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caso_cliente_id'), 'caso', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_caso_tipo_atendimento'), 'caso', ['tipo_atendimento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caso_tipo_atendimento'), table_name='caso')
    op.drop_index(op.f('ix_caso_cliente_id'), table_name='caso')
    op.drop_table('caso')
    # ### end Alembic commands ###
